# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app
COPY app.py /app
# Install minimal dependencies
RUN pip install --no-cache-dir fastmcp cryptography httpx
ENV PYTHONUNBUFFERED=1
CMD ["python", "app.py"]
