# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install only necessary dependencies
RUN pip install --no-cache-dir fastmcp cryptography httpx

# Copy application code
COPY app.py ./

# Create data directory
RUN mkdir -p data

# Unbuffered
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["fastmcp", "run", "app.py"]
