# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app
# Install only minimal dependencies
RUN pip install --no-cache-dir fastmcp httpx cryptography
COPY app.py ./
# Expose no port for stdio
CMD ["python", "app.py"]
